language: android

android:
  components:
    - tools
    - platform-tools
    - tools
  licences:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

    
install: cd application/ && ./gradlew build app